package agent

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/nanami/antisthenes/internal/agent/installable"
)

func registerAnsibleTools(r *ToolRegistry) {
	r.Register("ansible_check", func(args map[string]any) (string, error) {
		entry, ok := installable.Get("ansible")
		if !ok {
			return "ansible_check: ansible not in install catalog", nil
		}

		var b strings.Builder
		b.WriteString("ansible_check:\n")
		if bin, found := installable.ResolveBin(entry); found {
			b.WriteString("- ansible available: " + bin + "\n")
		} else {
			b.WriteString("- ansible: not found (venv or global)\n")
			b.WriteString("- install: install_tool with tool=ansible (creates .ansible-venv + pip install)\n")
		}

		_ = os.MkdirAll("playbooks", 0o755)
		_ = os.MkdirAll("logs/ansible", 0o755)
		b.WriteString("- dirs: playbooks/ and logs/ansible/ ensured\n")

		if installable.Available(entry) {
			b.WriteString("\nReady. Use ansible_generate_playbook or ansible_run_playbook.\n")
			b.WriteString("(Destructive runs should still go through policy approval.)\n")
		} else {
			b.WriteString("\nRun install_tool({tool: \"ansible\"}), then re-run ansible_check.\n")
		}
		return b.String(), nil
	})

	r.Register("ansible_run_playbook", func(args map[string]any) (string, error) {
		name, _ := args["name"].(string)
		playbookPath, _ := args["path"].(string)
		if playbookPath == "" {
			if name != "" {
				playbookPath = filepath.Join("playbooks", name+".yml")
			} else {
				return "ansible_run_playbook: 'name' or 'path' required", nil
			}
		}

		ansiblePlaybook, err := resolveAnsiblePlaybook()
		if err != nil {
			return "ansible_run_playbook: " + err.Error() + " Run install_tool with tool=ansible first.", nil
		}

		_ = os.MkdirAll("logs/ansible", 0o755)
		ts := time.Now().Unix()
		logPath := fmt.Sprintf("logs/ansible/run-%s-%d.log", strings.ReplaceAll(filepath.Base(playbookPath), ".yml", ""), ts)

		cmd := exec.Command(ansiblePlaybook, playbookPath)
		out, runErr := cmd.CombinedOutput()
		logContent := string(out)
		if runErr != nil {
			logContent += "\nError: " + runErr.Error()
		}
		_ = os.WriteFile(logPath, []byte(logContent), 0o644)

		tail := tailLines(logContent, 10)
		summary := fmt.Sprintf("ansible_run_playbook: executed %s\nLog: %s\n--- tail ---\n%s\n(Note: full policy approval recommended before destructive runs.)", playbookPath, logPath, tail)
		return summary, nil
	})

	r.Register("ansible_generate_playbook", func(args map[string]any) (string, error) {
		desc, _ := args["description"].(string)
		name, _ := args["name"].(string)
		if name == "" {
			name = "generated-" + fmt.Sprintf("%d", time.Now().Unix())
		}
		playbookPath := filepath.Join("playbooks", name+".yml")

		if _, err := os.Stat(playbookPath); err == nil {
			return "ansible_generate_playbook: duplicate exists at " + playbookPath + " (choose different name)", nil
		}

		_ = os.MkdirAll("playbooks", 0o755)
		_ = os.MkdirAll("logs/ansible", 0o755)

		playbook := fmt.Sprintf(`---
# Generated by ansible_generate_playbook
# Customize; place machine-specific data in host_vars/ or group_vars/ (never inline).
# Per ansible-playbook-development skill conventions.

- name: %s
  hosts: all
  gather_facts: true
  tasks:
    - name: Example generated task (edit as needed)
      debug:
        msg: "Generated from description: %s"
`, desc, desc)

		if err := os.WriteFile(playbookPath, []byte(playbook), 0o644); err != nil {
			return "generate write error: " + err.Error(), nil
		}

		ansiblePlaybook, err := resolveAnsiblePlaybook()
		if err != nil {
			return fmt.Sprintf("ansible_generate_playbook: created %s\nSyntax/lint: skipped (%s). Run install_tool with tool=ansible, then re-check.", playbookPath, err.Error()), nil
		}

		checkCmd := exec.Command(ansiblePlaybook, "--syntax-check", playbookPath)
		checkOut, checkErr := checkCmd.CombinedOutput()
		lintResult := string(checkOut)
		if checkErr != nil {
			lintResult += "\nSyntax check note: " + checkErr.Error()
		} else {
			lintResult = "Syntax check OK"
		}

		return fmt.Sprintf("ansible_generate_playbook: created %s\nSyntax/lint: %s\n(Dirs ensured; add roles/ host_vars/ as needed. Run ansible-lint manually for more if installed.)", playbookPath, lintResult), nil
	})
}

func resolveAnsiblePlaybook() (string, error) {
	entry, ok := installable.Get("ansible")
	if !ok {
		return "", fmt.Errorf("ansible not in catalog")
	}
	for _, bin := range entry.Bins {
		if bin != "ansible-playbook" {
			continue
		}
		if path, err := exec.LookPath(bin); err == nil {
			return path, nil
		}
		venvBin := filepath.Join(entry.VenvDir, "bin", bin)
		if _, err := os.Stat(venvBin); err == nil {
			return venvBin, nil
		}
	}
	return "", fmt.Errorf("ansible-playbook not found")
}
